server:
  port: 8848
  tomcat:
    basedir: logs
  servlet:
    context-path: /nacos

spring:
  datasource:
    platform: mysql
  security:
    enabled: true
  boot:
    admin:
      client:
        url: http://127.0.0.1:5001
        username: username
        password: password
        instance:
          service-host-type: ip
  application:
    name: @project.artifactId@
  main:
    allow-circular-references: true

db:
  num: 1
  user: ${MYSQL_USER:root}
  password: ${MYSQL_PWD:root}
  url:
    0: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:nacos_server}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true

nacos:
  core:
    auth:
      server:
        identity:
          key: serverIdentity
          value: security
      plugin.nacos.token.secret.key: SecretKey012345678901234567890123456789012345678901234567890123456789
      enabled: false
      system.type: nacos
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

useAddressServer: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        enabled: false
      elastic:
        enabled: false
